<?php
// $Id: notifications_content.module,v 1.4.2.9.2.36.2.18.2.27 2010/07/24 11:27:42 jareyero Exp $
/**
 * @file
 * Subscriptions to content events
 */

// Max number of elements per page for user account tabs
define('NOTIFICATIONS_CONTENT_PAGER', 20);

/**
 * Implementation of hook_menu_()
 */
function notifications_content_menu() {
  $items['admin/messaging/notifications/subscriptions/content'] = array(
    'title' => 'Content',
    'description' => 'Content subscriptions',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('notifications_content_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'notifications_content.pages.inc',
  );
  // User pages, will be disabled by default
  $items['user/%user/notifications/thread'] = array(
    'type' => MENU_LOCAL_TASK,
    'access callback' => FALSE,
    'title' => 'Thread',
    'page callback' => 'notifications_user_subscription_list_page',
    'page arguments' => array('thread', 1),
    'weight' => 10,
  );
  $items['user/%user/notifications/nodetype'] = array(
    'type' => MENU_LOCAL_TASK,
    'access callback' => FALSE,
    'title' => 'Content type',
    'page callback' => 'notifications_user_subscription_list_page',
    'page arguments' => array('nodetype', 1),
    'weight' => 10,
  );
  $items['user/%user/notifications/author'] = array(
    'type' => MENU_LOCAL_TASK,
    'access callback' => FALSE,
    'title' => t('Author'),
    'page callback' => 'notifications_user_subscription_list_page',
    'page arguments' => array('author', 1),
    'weight' => 10,
  );
  $items['user/%user/notifications/typeauthor'] = array(
    'type' => MENU_LOCAL_TASK,
    'access callback' => FALSE,
    'title' => t('Content type by author'),
    'page callback' => 'notifications_user_subscription_list_page',
    'page arguments' => array('typeauthor', 1),
    'weight' => 10,
  );
  $items['admin/messaging/notifications/events/configure'] = array(
    'title' => 'Configure',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access arguments' => array('administer site configuration'),
    'file' => 'notifications.admin.inc',
  );
  $items['admin/messaging/notifications/events/test'] = array(
    'title' => 'Test',
    'description' => 'Test event templates.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('notifications_content_test_template_form'),
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer notifications'),
    'file' => 'notifications_content.pages.inc',
  );
  return $items;
}

/**
 * Menu access callback
 */
function notifications_content_access($account, $perm) {
  global $user;
  return
    ($account->uid && $account->uid == $user->uid && user_access($perm)) ||
    (user_access('administer notifications') && user_access($perm, $account));
}

/**
 * Implementation of hook_permission()
 */
function notifications_content_permission() {
  return array(
    'subscribe to content' =>  array(
      'title' => t('Subscribe to content'),
      'description' => t('Subscribe to content posted or updated.'),
    ),
    'subscribe to content type' =>  array(
      'title' => t('Subscribe to content type'),
      'description' => t('Subscribe to all content from a content type.'),
    ),
    'subscribe to author' =>  array(
      'title' => t('Subscribe to author'),
      'description' => t('Subscribe to content posted by a given user.'),
    ),

  );
}

/**
 * Implementation of hook_help()
 */
function notifications_content_help($path, $arg) {
  if ($path == 'admin/messaging/notifications/content') {
    $output = '<p>' . t('Content subscriptions are subscriptions to nodes that will produce notifications when a node is posted or updated or when a comment is posted for that nodes. Notifications will be sent only for published content so if you need to be notified of unpublished content waiting for approval you better use Triggers and Actions or some other module for that.') . '</p>';
    $output .= '<p>'. t('On this page you can set which of the available subscription types are allowed. Alternatively you can select the <em>Set up for each content type</em> option and use the <a href="@content-type-settings">Administer Content types</a> page. These settings will be combined with permissions and other options (See user interface options if enabled) to determine which subscriptions will be finally available for users.', array('@content-type-settings' => url( 'admin/content/types'))) .'</p>';
    return $output;
  }
  elseif (array($arg[0], $arg[1], $arg[2], $arg[3]) == array('admin', 'messaging', 'template', 'edit') && ($group = $arg[4])) {
    switch ($group) {
      case 'notifications-digest-node-nid':
      case 'notifications-digest-node-type':
        $help = '<p>' . t('This is the format for each digest group. A message may consist on one or many of these groups:') . '</p>';
        $help .= '<small><pre>';
        $help .= t('Group title') . "\n";
        $help .= '- ' . t('Digest line.'). "\n";
        $help .= '- ' . t('Digest line.'). "\n";
        $help .= '-  ...'. "\n";
        $help .= t('Group footer') . "\n";
        $help .= '</pre></small>';
        return $help;     
    }    
  }
}

/**
 * Implementation of hook_form_alter().
 */
function notifications_content_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'comment_form':
      // Load the node which is possibly cached to get the node type
      $node = node_load($form['nid']['#value']);
      if (notifications_content_type_enabled($node->type)) {    
        if (notifications_event_enabled('node-comment')) {
          _notifications_content_add_disable_field($form);
        }
        // If editing the comment, add values to remember
        if (!empty($form['cid']['#value']) && !empty($form['admin']['status'])) {
          $form['notifications_comment_status'] = array('#type' => 'value', '#value' => $form['admin']['status']['#default_value']);
        }
      }

      break;   
    case 'node_type_form':
      if (isset($form['identity']['type'])) {
        // Hack for modules with different weights to add options here
        if (!isset($form['notifications'])) $form['notifications'] = array();
        $form['notifications'] += array(
          '#type' => 'fieldset',
          '#title' => t('Subscription settings'),
          '#collapsible' => TRUE,
          '#collapsed' => TRUE,
        );        
        $form['notifications']['notifications_content_type'] = array(
          '#type' => 'checkboxes',
          '#title' => t('Allowed subscription types'),
          '#default_value' => notifications_content_type_enabled($form['#node_type']->type),
          '#options' => _notifications_content_type_options(),
          '#description' => t('Enable different subscription options for this content type.'),
          '#weight' => -10,
        );
        if (!variable_get('notifications_content_per_type', 0)) {
          $form['notifications']['notifications_content_type']['#disabled'] = TRUE;
          $form['notifications']['notifications_content_type']['#description'] .= ' <strong>' . t('To enable these options check the <a href="@notifications-settings">Notifications content settings</a>', array('@notifications-settings' => url('admin/messaging/notifications/content'))) . '</strong>';
        }
      }
      break;      
    default:
      // Node form. Option to disable notifications
      /*
      if (isset($form['type']) && isset($form['#node']) && $form['type']['#value'] .'_node_form' == $form_id) {
        $node = $form['#node'];
        // Do not add if content type disabled, creating and create events disabled, updating and update events disabled
        if (notifications_content_type_enabled($node->type) && (empty($node->nid) && notifications_event_enabled('node-insert') || !empty($node->nid) && notifications_event_enabled('node-update'))) {
          _notifications_content_add_disable_field($form, !empty($node->notifications_content_disable));
        }
      }
      */
  }
}

/**
 * Add disable (skip notifications) field set
 */
function _notifications_content_add_disable_field(&$form, $default = 0) {
  if (user_access('skip notifications')) {
    // Add fieldset without affecting any other elements there
    $form['notifications']['#type'] = 'fieldset';
    $form['notifications']['#title'] = t('Notifications');
    $form['notifications']['#collapsible'] = TRUE;  
    $form['notifications']['notifications_content_disable'] = array(
      '#type'          => 'checkbox',
      '#title'         => t('Do not send notifications for this update.'),
      '#default_value' => $default,
    );
  }  
}

/**
  * Implementation of hook hook_content_extra_fields().
  *
  * Enables CCK (admin/content/types/CONTENT_TYPE/fields) to configure the
  * position of the notifications fieldset within the node.
  *
  * @ingroup hooks
  */
function notifications_content_content_extra_fields($type_name) {
  $extra = array();
  if (notifications_content_type_enabled($type_name) && (notifications_event_enabled('node-insert') || notifications_event_enabled('node-update'))) {
    $extra['notifications'] = array(
      'label' => t('Notifications'),
      'description' => t('Notifications module form.'),
      'weight' => 100,
      );
  }
  return $extra;
}

/**
 * Implementation of hook_theme()
 */
function notifications_content_theme() {
  return array(
    'notifications_content_type_settings' => array(
      'arguments' => array('element' => NULL),
      'file' => 'notifications_content.pages.inc',
    ),
  );  
}

/**
 * Implementation of hook_notifications()
 */
function notifications_content_notifications($op) {
  switch ($op) {
    case 'subscription types':
      // Some types may be globally disabled (for all content types), mark as such
      $disabled = !variable_get('notifications_content_per_type', 0);
      $types['content_thread'] = array(
        'title' => t('Thread'),
        'class' => 'Notifications_Node_Subscription',
        'access' => array('subscribe to content'),
        'description' => t('Subscribe to all changes and comments for a thread.'),
      );
      $types['content_type'] = array(
        'title' => t('Content type'),
        'class' => 'Notifications_Node_Type_Subscription',
        'access' => array('subscribe to content type'),
        'description' => t('Subscribe to all content of a given type.'),
      );
      $types['content_author'] = array(
        'title' => t('Author'),
        'class' => 'Notifications_Author_Subscription',
        'access' => array('subscribe to author'),
        'description' => t('Subscribe to all content submitted by a user.'),
      );
      // This is a complex type, combining two fields
      $types['content_type_author'] = array(
        'title' => t('Content type by author'),
        'class' => 'Notifications_Node_Type_Author_Subscription',
        'access' => array('subscribe to content', 'subscribe to author'),
        'description' => t('Subscribe to all content of a given type submitted by a user.'),
      );
      return $types;

    case 'field types':
      $fields['node:uid'] = array(
        'title' => t('Author'),
        'class' => 'Notifications_User_Field',
      );
      $fields['node:type'] = array(
        'title' => t('Node type'),
        'class' => 'Notifications_Node_Type_Field'
      );
      return $fields;

    case 'object types':
      // Define object types for use by events and subscriptions
      // Node and user are defined in the main notifications module
      $types['comment'] = array(
        'title' => t('Comment'),
        'class' => 'Notifications_Comment',
      );
      return $types;

    case 'event types':
      $types['node-post'] = array(
        'type' => 'node',
        'action' => 'post',
        'title' => t('Node post'),
        'class' => 'Notifications_Node_Post_Event',
        'template' => 'notifications-event-node-insert',
        'actions' => array('notifications_content_node_insert_action', 'notifications_content_node_update_action'),
      );
      $types['node-update'] = array(
        'type' => 'node',
        'action' => 'update',
        'class' => 'Notifications_Node_Update_Event',
        'title' => t('Node update'),
        'template' => 'notifications-event-node-update',
        'actions' => array('notifications_content_node_update_action'),
      );      
      $types['node-comment'] = array(
        'type' => 'node',
        'action' => 'comment',
        'class' => 'Notifications_Node_Comment_Event',
        'title' => t('Node comment'),
        'template' => 'notifications-event-node-comment',
        'actions' => array('notifications_content_comment_action'),
      );
      return $types;

    case 'message templates':
      // Node inserts are not grouped by node but all together. The digest will look like:
      //   New content has been submitted
      //   - Story Title1 by Author1
      //   - Event Title2 by Author2
      $types['notifications-event-node-insert'] = array(
        'title' => t('Template for node posts'),
        'class' => 'Notifications_Node_Insert_Template',
      );
      // These other events are grouped for each node. The digest will look like:
      //   Story: Title of the story
      //   - The story has been updated
      //   - New comment by User: Comment title
      $types['notifications-event-node-update'] = array(
        'title' => t('Template for node updates'),
        'class' => 'Notifications_Node_Update_Template',
      );
      $types['notifications-event-node-comment'] = array(
        'title' => t('Template for node comments'),
        'class' => 'Notifications_Node_Comment_Template',
      );      
      return $types;

    case 'event classes':
      return array('node' => t('Node'));
      
    case 'event actions':
      return array(
        'insert' => t('Creation'),
        'update' => t('Update'),
        'comment' => t('Comment'),
      );
  }
}

/**
 * Implements hook_action_info().
 */
function notifications_content_action_info() {
  return array(
    'notifications_content_node_insert_action' => array(
      'type' => 'notifications',
      'label' => t('Send content notifications'),
      'configurable' => FALSE,
      //'behavior' => array('changes_property'),
      'triggers' => array('node_insert'),
    ),
    'notifications_content_node_update_action' => array(
      'type' => 'notifications',
      'label' => t('Send content notifications'),
      'configurable' => FALSE,
      //'behavior' => array('changes_property'),
      'triggers' => array('node_update'),
    ),
    'notifications_content_comment_action' => array(
      'type' => 'notifications',
      'label' => t('Send comment notifications'),
      'configurable' => FALSE,
      //'behavior' => array('changes_property'),
      'triggers' => array('comment_insert', 'comment_update'),
    ),
  );
}

/**
 * Send content notificaitons
 *
 * @ingroup actions
 */
function notifications_content_node_insert_action($node, $context = array()) {
  $node = $context['node'];
  // Just for published nodes
  if (!empty($node->status)) {
    notifications_content_node_event('post', $node)->trigger();
  }
}

/**
 * Send content notificaitons
 *
 * @ingroup actions
 */
function notifications_content_node_update_action($node, $context = array()) {
  $node = $context['node'];
  // If not published before, send 'post' event, otherwhise, send 'update' event if published
  if (!empty($node->status)) {
    if (empty($node->notifications_status)) {
      notifications_content_node_event('post', $node)->trigger();
    }
    else {
      notifications_content_node_event('update', $node)->trigger();
    }
  }
}

/**
 * Build node event. We can have 'node-[type]' or plain 'node' events
 * 
 * We keep track of the events in this request so we return the same event if tried again
 * Events are not supossed to be triggered twice, see Notifications_Event::trigger()
 */
function notifications_content_node_event($action, $node) {
  $page = &drupal_static(__FUNCTION__);
  if (!isset($page[$action][$node->nid])) {
    if (notifications_event_type('node-' . $node->type . '-' . $action)) {
      $type = 'node-' . $node->type;
    }
    else {
      $type = 'node';
    }
    $page[$action][$node->nid] = notifications_event($type, $action)->add_object('node', $node);
  }
  return $page[$action][$node->nid];
}

/**
 * Send comment notificaitons
 *
 * @ingroup actions
 */
function notifications_content_comment_insert_action($node, $context = array()) {
  
}

/**
 * Send comment notificaitons
 *
 * @ingroup actions
 */
function notifications_content_comment_update_action($node, $context = array()) {
  
}

/**
 * Implementation of hook notifications_subscription()
 */
function notifications_content_notifications_subscription($op, $subscription = NULL) {
  switch ($op) {
    case 'access':
      // Check access control for subscription
      if (($conditions = $subscription->get_conditions()) && !empty($conditions['type'])) {
        // It seems to be a subscription for a content type
        return notifications_content_type_enabled($conditions['type'], $subscription->type);
      }
      break;

    case 'page objects':
      $objects = array();
      // Return objects on current page to which we can subscribe
      if (arg(0) == 'node' && is_numeric(arg(1)) && ($node = menu_get_object('node'))) {
        $objects[] = notifications_object('node', $node);  
      }
      return $objects;
      break;
  }  
}

/**
 * Implementation of hook_notifications_object_node()
 */
function notifications_content_notifications_object_node($op, $node, $account = NULL) {
  switch ($op) {
    case 'conditions':
      return array(
        'nid' => $node->nid,
        'type' => $node->type,
        'author' => $node->uid,
      );
    case 'subscriptions':
      // Return available subscription options for this node and this user account
      $options = array();
      // Thread
      if (notifications_content_type_enabled($node->type, 'thread')) {
        $options[] = Notifications_Subscription::build_instance('thread')
          ->set_name(t('This post')) // @todo this name should be in page objects
          ->add_field('node:nid', $node->nid);
      }
      // Content type subscriptions
      /*
      if (notifications_content_type_enabled($node->type, 'nodetype')) { 
        $options[] = array(
          'name' => t('Posts of type @type', array('@type' => notifications_content_type_name($node->type))),
          'type' => 'nodetype',
          'fields' => array('type' => $node->type),
        );
      }
      // Node author subscriptions
      if (notifications_content_type_enabled($node->type, 'author')) {
        $options[] = array(
          'name' => t('Posts by @name', array('@name' => _notifications_content_node_username($node))),
          'type' => 'author',
          'fields' => array('author' => $node->uid),
        );
      }
      // Subscribe to content type by author
      if (notifications_content_type_enabled($node->type, 'typeauthor')) {
        $options[] = array(
          'name' => t('@type posts by @name', array('@name' => _notifications_content_node_username($node), '@type' => notifications_content_type_name($node->type))),
          'type' => 'typeauthor',
          'fields' => array('author' => $node->uid, 'type' => $node->type),
        );
      }
      */
      return $options;
      break;
  }
}

/**
 * Implementation of hook_notifications_object_user()
 */
function notifications_content_notifications_object_user($op, $user, $account = NULL) {
  switch ($op) {
    case 'conditions':
      // Condition fields for subscriptions to this object type (user)
      return array(
        'uid' => $user->uid,
        'author' => $user->uid,
      );
    case 'subscriptions':
      // Option subscriptions to user account. Checking permissions here will save some processing.
      $options = array();
      // All posts by author
      if (!$account || user_access('subscribe to author', $account)) {
        $options[] = array(
          'name' => t('All posts by @name', array('@name' => $user->name)),
          'type' => 'author',
          'fields' => array('author' => $user->uid),
        );
      }
      // Content types with author subscriptions
      if (!$account || user_access('subscribe to content type and author', $account)) {
        foreach (notifications_content_types('typeauthor') as $type => $type_name) {
          $options[] = array(
            'name' => t('@type posts by @name', array('@name' => $user->name, '@type' => $type_name)),
            'type' => 'typeauthor',
            'fields' => array('author' => $author->uid, 'type' => $type),
          );
        }
      }
      return $options;      
  }
  
}


/**
 * List (enabled) subscription options for content types
 * 
 * @param $enabled
 *   Whether to get only enabled subscription types or all of them
 */
function _notifications_content_type_options($enabled = TRUE) {
  if ($types = notifications_subscription_type()) {
    if ($enabled) {
      $types = array_intersect_key($types, notifications_subscription_type_enabled());
    }
    if ($types) {
      // Only node subscriptions
      if ($types = notifications_array_filter($types, array('event_type' => 'node'))) {
        if ($types = notifications_array_filter($types, array('custom' => TRUE), TRUE)) {
          return array_map('notifications_format_title_description', $types);
        }
      }
    }
  }
  return array();
}

/**
 * Get username from node (and add it to the node object)
 */
function _notifications_content_node_username($node) {
  // If the node comes from a page query, it may have an author name, otherwise we set it
  if (empty($node->name)) {      
    if ($author = notifications_load_user($node->uid)) {
      $node->name = $author->name;
    }
    else {
      $node->name = t('Unknown');
    }
  }
  return $node->name;
}

/**
 * Implementation of hook_node_load()
 */
function notifications_content_node_load($nodes, $types) {
  // Keep track of previous status for nodes
  foreach ($nodes as $node) {
    $node->notifications_status = $node->status;
  }
}
/**
 * Implementation of hook_node_delete()
 */
function notifications_content_node_delete($node) {
  // Remove all subscriptions for this node
  Notifications_Subscription::delete_multiple(array(), array('node:nid' => $node->nid), FALSE);  
}

/**
 * Implementation of hook_comment().
 * 
 * This is a bit tricky because we just want to send notifications when they are published. Quick reminder:
 * - Normal 'insert' operations are followed by a 'publish' one so we don't process that ones.
 * - Normal 'update' operations are followed by a 'publish' whatever the previous status was
 * - For 'publish' operations we notify if the comment was not published before.
 * 
 * Note that we don't take the comment by ref so we don't change it when it's an array
 **/
function notifications_content_comment($comment, $op) {
  // $comment can be an object or an array.
  $comment = (object)$comment;

  if ($op == 'publish' && empty($comment->notifications_content_disable) && notifications_event_enabled('node-comment') &&
    (!isset($comment->notifications_comment_status) || !empty($comment->notifications_comment_status)) ) {
    // Check that the node is published and comment notifications are enabled for this node type
    $node = node_load($comment->nid);    
    if ($node->status && notifications_content_type_enabled($node->type)) {
      $event = array(
        'uid' => $comment->uid, // For this special case the event actor is the user who posts the comment
        'module' => 'node',
        'type' => 'node',
        'oid' => $node->nid,
        'action' => 'comment',
      );
      notifications_event($event, array('node' => $node, 'comment' => $comment));   
    }    
  }
}

/**
 * Implementation of hook node_type_delete().
 */
function notifications_content_node_type_delete($info) {
  // Remove all subscriptions for this node type
  Notifications_Subscription::delete_multiple(array(), array('node:type' => $info->type));  
}

/**
 * Implementation of hook node_type_update().
 */
function hook_node_type_update($info) {
  if (!empty($info->old_type) && $info->old_type != $info->type) {
    db_update('notifications_subscription_fields')
    ->fields(array('value' => $info->type))
    ->condition('type', 'node:type')
    ->condition('value', $info->old_type)
    ->execute();
  }
}

/**
 * Load comments with caching
 * @ TODO See if this may be some use, or drop
 */
function notifications_content_comment_load($cid) {
  $cache = &drupal_static(__FUNCTION__);
  if (!$cache || !array_key_exists($cid, $cache)) {
    $comment = db_fetch_object(db_query('SELECT c.*, u.uid, u.name AS registered_name, u.data FROM {comments} c INNER JOIN {users} u ON c.uid = u.uid WHERE c.cid = %d', $cid));
    if ($comment) {
      $comment = drupal_unpack($comment);
      $comment->name = $comment->uid ? $comment->registered_name : $comment->name;
    }
    $cache[$cid] = $comment;
  }
  return $cache[$cid];
}

/**
 * Mapping from comment cid to title
 */
function notifications_content_comment_cid2title($cid, $html = FALSE) {
  if ($comment = notifications_content_comment_load($cid)) {
    return $html ? l($comment->subject, "node/$comment->nid", array('fragment' => "comment-$comment->cid")) : check_plain($comment->subject);
  }
  else {
    return t('Not found');
  }
}

/**
 * Get content types available for subscriptions to content type
 * 
 * @param $subs_type
 *   Optional type of subscription for which to find allowed content types.
 *   If none, return all content types for which any subscription type is enabled.
 */
function notifications_content_types($subs_type = NULL) {
  // Get list of available node types, all of them will be allowed by default
  $types = array();

  foreach (notifications_content_type_name() as $key => $name) {
    if (notifications_content_type_enabled($key, $subs_type)) {
      $types[$key] = $name;
    }
  }

  return $types;  
}

/**
 * Get list of translated content type names
 */
function notifications_content_type_name($type = NULL) {
  static $types;
  
  if (!isset($types)) {
    foreach (node_get_types('names') as $key => $name) {
      $types[$key] = notifications_translate("type:$key:name", $name , NULL, 'nodetype');
    }
  }
 
  return $type ? $types[$type] : $types;
}

/**
 * Get subscription options for this content type
 * 
 * PHP Note: We need to use strict checking for in_array(), http://es.php.net/manual/en/function.in-array.php#91911
 * 
 * @param $type
 *   Optional content type to return info for, global notifications defaults if none.
 * @param $option
 *   Optional option to return for the given content type or the defaults, defaults to returning all settings for the type.
 * @param $disabled
 *   Check also for globally disabled subscription types
 */
function notifications_content_type_enabled($type = NULL, $option = NULL, $disabled = FALSE) {
  $settings = variable_get('notifications_content_type', array());
  if ($type) {
    if (!$disabled && !notifications_subscription_type_enabled($type)) {
      $settings = array();
    }
    elseif (variable_get('notifications_content_per_type', 0)) {
      $settings = variable_get('notifications_content_type_' . $type, $settings);
    }
  }
  elseif (!$disabled) {
    // Take out globally disabled subscriptions
    $settings = array_intersect($settings, notifications_subscription_type_enabled());
  }
  if ($option) {
    return in_array($option, $settings, TRUE);
  }
  else {
    // We filter the array to return an empty one when no option enabled
    return array_filter($settings);
  }
}

/**
 * Determine whether the specified user may view the specified node.
 *
 * Does a user switching and checks for node permissions. Looking for a better way
 * but it seems that all the node_access hooks cant be invokes without this.
 */
function notifications_content_node_allow($account, $node) {
  static $access;
  
  if (!$node) return FALSE;

  if (!isset($access[$account->uid][$node->nid])) {
    $access[$account->uid][$node->nid] = node_access('view', $node, $account);
  }

  return $access[$account->uid][$node->nid];
}

/**
 * Determine whether the specified user may view the specified comment.
 *
 * Does a user switching and checks for node permissions. Looking for a better way
 * but it seems that all the node_access hooks cant be invokes without this.
 */
function notifications_content_comment_allow($account, $comment) {
  static $access;
  $comment = is_object($comment) ? $comment : db_fetch_object(db_query("SELECT * FROM {comments} WHERE cid = %d", $comment));
  if (!isset($access[$account->uid][$comment->cid])) {
    if (($account->uid == $comment->uid || $comment->status == COMMENT_PUBLISHED) && user_access('access comments', $account) || user_access('administer comments', $account)) {
      $access[$account->uid][$comment->cid] = TRUE;
    }
    else {
      $access[$account->uid][$comment->cid] = FALSE;
    }
  }
  return $access[$account->uid][$comment->cid];
}

/**
 * Notifications object access callback. Determine whether the specified user may view the specified comment.
 */
function notifications_content_comment_access($comment, $account) {
  // User can access own comments, other comments if published and has access, or can administer comments
  return (
    ($account->uid == $comment->uid || $comment->status == COMMENT_PUBLISHED && user_access('access comments', $account))
    || user_access('administer comments', $account)
  )
  // But all that if and only if the user can access the node too
  && notifications_object_access('node', $comment->nid, $account);
}